CREATE DATABASE IF NOT EXISTS employee;
USE employee;

CREATE TABLE IF NOT EXISTS emp_record_table(
    EMP_ID VARCHAR(6) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    DEPT VARCHAR(20) NOT NULL,
    EXP INT NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    CONTINENT VARCHAR(20) NOT NULL,
    SALARY INT NOT NULL,
    EMP_RATING INT NOT NULL,
    MANAGER_ID VARCHAR(6) NOT NULL,
    PROJ_ID VARCHAR(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS proj_table(
    PROJ_ID VARCHAR(6) NOT NULL,
    PROJ_Name VARCHAR(30) NOT NULL,
    DOMAIN VARCHAR(30) NOT NULL,
    START_DATE DATE NOT NULL,
    CLOSURE_DATE DATE NOT NULL,
    DEV_QTR INT NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Data_science_team(
    EMP_ID VARCHAR(6) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    DEPT VARCHAR(20) NOT NULL,
    EXP INT NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    CONTINENT VARCHAR(20) NOT NULL
)

